config/routes.rb
Playgrounds::Application.routes.draw do
  resources :equipment

  resources :playgrounds do
    resources :pg_pictures
  end

  root :to => 'playgrounds#index'
  
  devise_for :users

end

app/models/equipment.rb
class Equipment < ActiveRecord::Base
  attr_accessible :eqname
end

app/models/pg_picture.rb
#require 'file_size_validator'
class PgPicture < ActiveRecord::Base
  attr_accessible :image, :playgrounds_id, :latitude, :longitude, :place
  belongs_to :playground
  mount_uploader :image, ImageUploader
  geocoded_by :place
  reverse_geocoded_by :latitude, :longitude, :address => :place
  #validates :file_size => { :maximum => 1.5.megabytes.to_i }

  before_save :get_geocode, :reverse_geocode
  
  
  private
    def get_geocode
      if image.present?
        
        img = Magick::Image.read(image.path)[0]
        
        img_lat = img.get_exif_by_entry('GPSLatitude')[0][1].split(', ') rescue nil
        img_lng = img.get_exif_by_entry('GPSLongitude')[0][1].split(', ') rescue nil
        
        logger.debug "img_lat: #{img_lat}"


        lat_ref = img.get_exif_by_entry('GPSLatitudeRef')[0][1] rescue nil
        lng_ref = img.get_exif_by_entry('GPSLongitudeRef')[0][1] rescue nil

        return unless img_lat && img_lng && lat_ref && lng_ref

        latitude = to_frac(img_lat[0]) + (to_frac(img_lat[1])/60) + (to_frac(img_lat[2])/3600)
        longitude = to_frac(img_lng[0]) + (to_frac(img_lng[1])/60) + (to_frac(img_lng[2])/3600)

        latitude = latitude * -1 if lat_ref == 'S'  # (N is +, S is -)
        longitude = longitude * -1 if lng_ref == 'W'   # (W is -, E is +)

        self.latitude = latitude
        self.longitude = longitude
        
        #img = Magick::Image.read(image)
        
        #tempPix = EXIFR::JPEG.new(image)
        #self.latitude = EXIFR::JPEG.new(image.path.to_s).gps_lat
        #self.longtitude = tempPix.gps_lng
      end
    end
    
    def to_frac(frac)
      numerator, denominator = frac.split('/').map(&:to_f)
      denominator ||= 1
      numerator/denominator
    end
  
end

app/models/playground.rb
class Playground < ActiveRecord::Base
  attr_accessible :country, :latitude, :longitude, :name, :play_id, :state, :suburb, :country, :place, :address
  has_many :pg_pictures
  geocoded_by :address
  reverse_geocoded_by :latitude, :longitude
  
  after_validation :geocode, :reverse_geocode


  def set_playground_location(latitude, longitude, place)
    self.latitude = latitude
    self.longitude = longitude
    logger.debug "!!!!!!!!!!!!!!!!!!!!!!!! place being saved to playground is: #{place}"
    self.address = place
    self.save
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/equipment_controller.rb
class EquipmentController < ApplicationController
  # GET /equipment
  # GET /equipment.json
  def index
    @equipment = Equipment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @equipment }
    end
  end

  # GET /equipment/1
  # GET /equipment/1.json
  def show
    @equipment = Equipment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @equipment }
    end
  end

  # GET /equipment/new
  # GET /equipment/new.json
  def new
    @equipment = Equipment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @equipment }
    end
  end

  # GET /equipment/1/edit
  def edit
    @equipment = Equipment.find(params[:id])
  end

  # POST /equipment
  # POST /equipment.json
  def create
    @equipment = Equipment.new(params[:equipment])

    respond_to do |format|
      if @equipment.save
        format.html { redirect_to @equipment, notice: 'Equipment was successfully created.' }
        format.json { render json: @equipment, status: :created, location: @equipment }
      else
        format.html { render action: "new" }
        format.json { render json: @equipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /equipment/1
  # PUT /equipment/1.json
  def update
    @equipment = Equipment.find(params[:id])

    respond_to do |format|
      if @equipment.update_attributes(params[:equipment])
        format.html { redirect_to @equipment, notice: 'Equipment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @equipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /equipment/1
  # DELETE /equipment/1.json
  def destroy
    @equipment = Equipment.find(params[:id])
    @equipment.destroy

    respond_to do |format|
      format.html { redirect_to equipment_index_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pg_pictures_controller.rb
class PgPicturesController < ApplicationController
  before_filter :find_playground
  
  def new
    @pg_picture = @playground.pg_pictures.new
  end
  
  def create
    @pg_picture = @playground.pg_pictures.new(params[:pg_picture])
    

    
    if @pg_picture.save
      
      flash[:notice] = "Picture was uploaded"
      logger.debug "XXX checking if #{@playground.name} has an address"
      if(not @playground.address.length > 0)
        logger.debug "XXX about to set the address"
        @playground.set_playground_location(@pg_picture.latitude, @pg_picture.longitude, @pg_picture.place)
      end
      redirect_to @playground
    else
      flash[:notice] = "Picture was not successfully uploaded"
      redirect_to @playground
    end
  end
  
  def destroy
    @pg_picture = @playground.pg_pictures.find(params[:id])
    @pg_picture.destroy
    flash[:notice] = "Picture has been deleted"
    redirect_to @playground
  end
  
  protected 
    def find_playground
      @playground = Playground.find(params[:playground_id])
    end
  

  
end

app/controllers/playgrounds_controller.rb
class PlaygroundsController < ApplicationController

  def index
    @playgrounds = Playground.all
  end

  def new
    @playground = Playground.new
  end

  def create
    @playground = Playground.new(params[:playground])
    @playground.save
    flash[:notice] = "Playground has been created"
    redirect_to @playground
  end

  def edit
    @playground = Playground.find(params[:id])
  end
  
  def update
    @playground = Playground.find(params[:id])
    if @playground.update_attributes(params[:playground])
      redirect_to @playground
    else
      flash[:notice] = "Errors prevented this from being updated"
      redirect_to @playground
    end
  end
  
  def show
    @playground = Playground.find(params[:id])
    @pg_pix = @playground.pg_pictures.all
  end
  


  protected

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/helpers/pg_pictures_helper.rb
module PgPicturesHelper
end

app/helpers/playgrounds_helper.rb
module PlaygroundsHelper
  

  
end

app/views/equipment/_form.html.erb
<%= form_for(@equipment) do |f| %>
  <% if @equipment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@equipment.errors.count, "error") %> prohibited this equipment from being saved:</h2>

      <ul>
      <% @equipment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :eqname %><br />
    <%= f.text_field :eqname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/equipment/edit.html.erb
<h1>Editing equipment</h1>

<%= render 'form' %>

<%= link_to 'Show', @equipment %> |
<%= link_to 'Back', equipment_index_path %>

app/views/equipment/index.html.erb
<h1>Listing equipment</h1>

<table>
  <tr>
    <th>Equipment Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @equipment.each do |equipment| %>
  <tr>
    <td><%= equipment.eqname %></td>
    <td><%= link_to 'Show', equipment %></td>
    <td><%= link_to 'Edit', edit_equipment_path(equipment) %></td>
    <td><%= link_to 'Destroy', equipment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Equipment', new_equipment_path %>

app/views/equipment/new.html.erb
<h1>New equipment</h1>

<%= render 'form' %>

<%= link_to 'Back', equipment_index_path %>

app/views/equipment/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Equipment Name:</b>
  <%= @equipment.eqname %>
</p>


<%= link_to 'Edit', edit_equipment_path(@equipment) %> |
<%= link_to 'Back', equipment_index_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Playgrounds</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div id="wrapper">
        <div id="header"> 
            <div>
                <h1><%= link_to "PG Required", playgrounds_path%></h1>
            </div>
            <div id="login_logout_box">
                <% if user_signed_in? %>
                  Logged in as <strong><%= current_user.email %></strong>.
                  <%= link_to 'Edit profile', edit_user_registration_path %> |
                  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
                <% else %>
                  <%= link_to "Sign up", new_user_registration_path %> |
                  <%= link_to "Login", new_user_session_path %>
                <% end %>
                <br />
                <strong>Admin Tools</strong><br />
                <ul>
                    <li><%= link_to 'View Equipment List', equipment_index_path %></li>
                </ul>
            </div>
        </div>
        
        <div id="content"> 
            <div id="flash">
                <p class="notice"><%= notice %></p>
                <p class="alert"><%= alert %></p>
            </div>
            <div> 
                <%= yield %>
            </div>
        </div>

        <div id="footer"> insert footer here eventually
        
    
        </div>
    </div>
</body>
</html>

app/views/pg_pictures/new.html.erb
<h2>Add a new picture to <%= @playground.name %></h2>
<%= form_for [@playground, @pg_picture] do |f| %>
    <%= f.label :image%>
    <%= f.file_field :image %><br />
    
    <%= f.submit %>
<% end %>

<%= link_to "Return to All Playgrounds", playgrounds_path%>

app/views/playgrounds/_form.html.erb
<%= form_for @playground do |f| %>


    <%= f.label :name %>
    <%= f.text_field :name %><br />
    
    <%= f.label :suburb %>
    <%= f.text_field :suburb %><br />
    
    <%= f.label :state %>
    <%= f.text_field :state %><br />
    <%= f.label :country %>
    <%= f.text_field :country %><br />

<% logger.debug "XXXXXXX: the value of :thingie is: #{from}"%>
    <% if from == "from_edit" %>
        <%= f.label :latitude%>
        <%= f.text_field :latitude %><br />
        <%= f.label :longitude %>
        <%= f.text_field :longitude %><br />
        <%= f.label :address%>
        <%= f.text_field :address %><br />
    <% end %>
    <%= f.submit "Submit"%>
    
<% end %>

app/views/playgrounds/edit.html.erb
<h2>Edit the <%= @playground.name %> details</h2>

<%= render :partial => 'form', :locals => {:from => "from_edit"} %>

app/views/playgrounds/index.html.erb
<h1>All Playgrounds</h1>

<ul>
<% @playgrounds.each do |pg| %>
    <li><%= link_to pg.name, playground_path(pg.id) %> in <%= pg.suburb%>, <%= pg.state%>, <%= pg.country%></li>
    <% if pg.address %>
        <ul>
        <% closeby = pg.nearbys(1) %>
        <% if closeby.size > 0 %>
            <% for spot in closeby %>
                <li><%= link_to spot.name, spot %></li>
            <% end %>
        <% else %>
            <li>There are no nearby playgrounds</li>
        <% end %>
        </ul>
    <% end %>
<% end %>
    <li><%= link_to 'Submit a new playground', new_playground_path %>
</ul>

app/views/playgrounds/new.html.erb
<h2>Tell the world about a playground</h2>

<%= render :partial => 'form' %>

app/views/playgrounds/show.html.erb
<h2><%= @playground.name %></h2>

<div>


<p>Located in: <%= @playground.suburb %>, <%= @playground.state %>, <%= @playground.country %><br />
Address by geocode: <%= @playground.address %><br />
Geocode location: (<%=@playground.latitude%>, <%=@playground.longitude%>)<br />
<%= link_to "Change this playground's details", edit_playground_path(@playground) %>
</p>

</div>

<div>
    <%= "Showing #{pluralize(@pg_pix.size, 'picture')}" %>
    <% @pg_pix.each do |pix| %>
        <p>
            Image ID is: <%= pix.id%><br />
            <%= image_tag pix.image_url(:thumb).to_s %><br />
            <% if pix.latitude && pix.longitude %>
                <%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{pix.latitude}%2C#{pix.longitude}" %><br />
                Address: <%= pix.place %>
                Latitude - Longitude: <%= pix.latitude %> - <%= pix.longitude %><br />
            <% end %>

            <%= button_to "Delete this picture", playground_pg_picture_path(@playground, pix), :method => "delete", :data => {:confirm => "Are you sure you want to delete this picture?"} %>
        </p>
    <% end %>
    <p><%= link_to "Add a picture", new_playground_pg_picture_path(@playground)%>
    </p>
</div>    
    
<p><%= link_to "Return to all playgrounds", playgrounds_path %>
</p>